Feature: Sunny day Scenarios -To retrieve all the accounts available in the given session

@RetrieveAccounts @TestAccountData
Scenario: To retieve the Accounts with valid session from bank with where consent is required
Given I make a GET request to /ics/v3/accounts
And I set header accept to application/json
And I set header authorization to 'Bearer $S{TOKEN}'
And I set header x-session-id to session_id
And I set header x-device-id to $M{App.device_id}
And I receive a response
Then I expect response body should contain href

Scenario: To retrieve accounts with valid session from bank with no consent required
Given I make a GET request to ACCOUNT_URL
And I set header accept to application/json
And I set header authorization to Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ2MmFQNDdIQXVTUi1qWmR5U3otNDVDV2RaOFhiWGFBMXNDbWhLbWtJLXRvIn0.eyJleHAiOjE3MDEwMjUxNzAsImlhdCI6MTcwMDkzODc3MCwianRpIjoiYTM2ZGE3YzAtNWMxMi00MmRiLTkxNDYtOGJlZDUzZmRhNjg5IiwiaXNzIjoiaHR0cHM6Ly9zYW5kYm94Lm5lb25vbWljcy5pby9yZWFsbXMvc2FuZGJveCIsInN1YiI6IjZmZDM1M2RmLTA0MWYtNDE2ZS05NThmLTFhMTk4MTJjOGIwYyIsInR5cCI6IkJlYXJlciIsImF6cCI6ImQ5ZjY1OWJhLTQ5OTgtNDdjMS1iZTkzLWI0OTA5MmNkZDFjMCIsInNlc3Npb25fc3RhdGUiOiI2MzBjZjQwNC1iOGQzLTQ0YTctODUwNC0xOGJhNzA5ZTE5MjciLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsicGlzcCIsImFpc3AiXX0sInNjb3BlIjoiYmFucWJyaWRnZV9jbGllbnQiLCJzaWQiOiI2MzBjZjQwNC1iOGQzLTQ0YTctODUwNC0xOGJhNzA5ZTE5MjciLCJvcmdhbml6YXRpb25JZCI6Ijg0ZDhlMjM0LTE4M2EtNDZlNC05M2I1LWUzN2MwMzA4NGRkNSIsImNsaWVudEhvc3QiOiIxOTMuOTAuMTEwLjQzIiwiY2tpZCI6IjFhNDE4M2YxLTIyNWQtNDJiOC1iOTMwLWM2MDA1ZjgxMDgyNCIsImNsaWVudEFkZHJlc3MiOiIxOTMuOTAuMTEwLjQzIiwiY2xpZW50X2lkIjoiZDlmNjU5YmEtNDk5OC00N2MxLWJlOTMtYjQ5MDkyY2RkMWMwIn0.dJJS4dd6kS6x_EDQ9liv7PSc57k4w-iQn8DRRcSqfJJ2U5i9hU0ZamKS5eIEZCcv32inOrubIdaMS-S3BS8O00tYbuXOakHqPiWYoohvamWgmYKmyRua-EErHdyxtNvQn1JpOeaa_JVQWF6WPJ6zJe1LFAkcijf2q7N0FxgVQHowqVZ0E7Tap0C_dyAJrE-hJLrfZqev77kLGeBdkgkPrK3nAMFfHDZzc0O_js271FwExDP48LlXH59iiyc7X7vHVcJfGxqTgWqd8kHivNuOJk8-g6F--84181OMdOMk70ey06fr-SazjhKZ31GO-8ox573N8YvZl0dEAwo8DHy_qQ
And I set header x-session-id to example_id_for_quickstart
And I set header x-device-id to 0a1b6794-6fbb-4f08-bb42-e6e36932b95b
And I receive a response
Then I expect response body should contain iban

